spring.datasource.url=jdbc:sqlite:web_deria.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Aquí está la magia: 'update' crea la tabla si no existe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true