# Deshabilitamos la autoconfiguración de base de datos temporalmente
# ya que JPA y PostgreSQL están en el pom.xml pero aún no configurados.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Puerto por defecto (opcional)
server.port=8080
